framework:
    workflows:
        project:
            type: 'state_machine'
            marking_store:
                type: single_state
                arguments:
                    - status
            supports:
                - App\Project\Project
            places:
                - 'completion_in_progress'
                - 'to_validate'
                - 'validated'
                - 'aborted'
            transitions:
                to_validate:
                    from: 'completion_in_progress'
                    to: 'to_validate'
                validated:
                    from: 'to_validate'
                    to:   'validated'
                aborted:
                    from: ['completion_in_progress', 'validated']
                    to:   'aborted'

